set COUNTRY_CODE=BEN
set RASTER_GRID_PATH=D:\GRID\ReferenceRasters\ben_px_area_100m.tif
set BUILDING_FOOTPRINT_SHAPEFILE_PATHS=D:\GRID\BEN\ECOPIA\AFRICA_BENIN_building_year2.gdb\AFRICA_BENIN_building_32631_year2
set RELEASE_DATE=20201222
set CODE_VERSION=ALPHA
set METADATA_DIR=D:\GRID\metadata

