set COUNTRY_CODE=CIV
set RASTER_GRID_PATH=D:\GRID\ReferenceRasters\civ_px_area_100m.tif
set BUILDING_FOOTPRINT_SHAPEFILE_PATHS=D:\GRID\CIV\DIGITAL_GLOBE\AFRICA_SIERRA_LEONE_building_32628.shp
set RELEASE_DATE=20200403
set CODE_VERSION=V02
set METADATA_DIR=D:\GRID\metadata

