set COUNTRY_CODE=DRC
set CODE_VERSION=V02
set RELEASE_DATE=20200114
set RASTER_GRID_PATH=D:\GRID\ReferenceRasters\drc_px_area_100m.tif
set BUILDING_FOOTPRINT_SHAPEFILE_PATHS=D:\GRID\DRC\DIGITAL_GLOBE\DRC_BF_all.shp