set COUNTRY_CODE=ETH
set RASTER_GRID_PATH=D:\GRID\ReferenceRasters\eth_px_area_100m.tif
set BUILDING_FOOTPRINT_SHAPEFILE_PATHS=D:\GRID\ETH\ECOPIA\AFRICA_ETHIOPIA_building_32638.shp;D:\GRID\ETH\ECOPIA\AFRICA_ETHIOPIA_building_32636.shp;D:\GRID\ETH\ECOPIA\AFRICA_ETHIOPIA_building_22_32637.shp;D:\GRID\ETH\ECOPIA\AFRICA_ETHIOPIA_building_21_32637.shp;D:\GRID\ETH\ECOPIA\AFRICA_ETHIOPIA_building_3_32637.shp;D:\GRID\ETH\ECOPIA\AFRICA_ETHIOPIA_building_1_32637.shp
set RELEASE_DATE=20200630
set CODE_VERSION=V02
set METADATA_DIR=D:\GRID\metadata

