set COUNTRY_CODE=GMB
set RASTER_GRID_PATH=D:\GRID\ReferenceRasters\gmb_px_area_100m.tif
set BUILDING_FOOTPRINT_SHAPEFILE_PATHS=D:\GRID\GMB\ECOPIA\AFRICA_GAMBIA_building_32628.shp
set RELEASE_DATE=20200214
set CODE_VERSION=V02
set METADATA_DIR=D:\GRID\metadata

