set COUNTRY_CODE=KEN
set RASTER_GRID_PATH=D:\GRID\ReferenceRasters\ken_px_area_100m.tif
set BUILDING_FOOTPRINT_SHAPEFILE_PATHS=D:\GRID\KEN\ECOPIA\AFRICA_KENYA_building_32636.shp;D:\GRID\KEN\ECOPIA\AFRICA_KENYA_building_32637.shp;D:\GRID\KEN\ECOPIA\AFRICA_KENYA_building_32736.shp;D:\GRID\KEN\ECOPIA\AFRICA_KENYA_building_32737.shp
set RELEASE_DATE=20200603
set CODE_VERSION=V02
set METADATA_DIR=D:\GRID\metadata

