set COUNTRY_CODE=LBR
set RASTER_GRID_PATH=D:\GRID\ReferenceRasters\lbr_px_area_100m.tif
set BUILDING_FOOTPRINT_SHAPEFILE_PATHS=D:\GRID\LBR\ECOPIA\AFRICA_LIBERIA_building_32629.shp
set RELEASE_DATE=20200114
set CODE_VERSION=V02
set METADATA_DIR=D:\GRID\metadata

