set COUNTRY_CODE=MDG
set RASTER_GRID_PATH=D:\GRID\ReferenceRasters\mdg_px_area_100m.tif
set BUILDING_FOOTPRINT_SHAPEFILE_PATHS=D:\GRID\MDG\ECOPIA\AFRICA_MADAGASCAR_building_32738.shp;D:\GRID\MDG\ECOPIA\AFRICA_MADAGASCAR_building_32739.shp
set RELEASE_DATE=20200323
set CODE_VERSION=V02
set METADATA_DIR=D:\GRID\metadata

