set COUNTRY_CODE=MLI
set RASTER_GRID_PATH=D:\GRID\ReferenceRasters\mli_px_area_100m.tif
set BUILDING_FOOTPRINT_SHAPEFILE_PATHS=D:\GRID\MLI\DIGITAL_GLOBE\AFRICA_MALI_building_32628.dbf;D:\GRID\MLI\DIGITAL_GLOBE\AFRICA_MALI_building_32629.dbf;D:\GRID\MLI\DIGITAL_GLOBE\AFRICA_MALI_building_32630.dbf;D:\GRID\MLI\DIGITAL_GLOBE\AFRICA_MALI_building_32631.dbf
set RELEASE_DATE=20200114
set CODE_VERSION=V02
set METADATA_DIR=D:\GRID\metadata

