set COUNTRY_CODE=MOZ
set RASTER_GRID_PATH=D:\GRID\ReferenceRasters\moz_px_area_100m.tif
set BUILDING_FOOTPRINT_SHAPEFILE_PATHS=D:\GRID\MOZ\ECOPIA\AFRICA_MOZAMBIQUE_building_32736.shp;D:\GRID\MOZ\ECOPIA\AFRICA_MOZAMBIQUE_building_32737.shp
set RELEASE_DATE=20200304
set CODE_VERSION=V02
set METADATA_DIR=D:\GRID\metadata

