set COUNTRY_CODE=MWI
set RASTER_GRID_PATH=D:\GRID\ReferenceRasters\mwi_px_area_100m.tif
set BUILDING_FOOTPRINT_SHAPEFILE_PATHS=D:\GRID\MWI\ECOPIA\AFRICA_MALAWI_building_32736.shp
set RELEASE_DATE=20200221
set CODE_VERSION=V02
set METADATA_DIR=D:\GRID\metadata

