set COUNTRY_CODE=NER
set RASTER_GRID_PATH=D:\GRID\ReferenceRasters\ner_px_area_100m.tif
set BUILDING_FOOTPRINT_SHAPEFILE_PATHS=D:\GRID\NER\ECOPIA\AFRICA_NIGER_building_32631.shp;D:\GRID\NER\ECOPIA\AFRICA_NIGER_building_32632.shp;D:\GRID\NER\ECOPIA\AFRICA_NIGER_building_32633.shp
set CODE_VERSION=V02
set RELEASE_DATE=20200114

