set COUNTRY_CODE=NGA
set RASTER_GRID_PATH=D:\GRID\ReferenceRasters\nga_px_area_100m.tif
set BUILDING_FOOTPRINT_SHAPEFILE_PATHS=D:\GRID\NGA\ECOPIA\AFRICA_NIGERIA_P2_building_32632_1.shp
set RELEASE_DATE=20200319
set CODE_VERSION=V02
set METADATA_DIR=D:\GRID\metadata

