set COUNTRY_CODE=SDN
set RASTER_GRID_PATH=D:\GRID\ReferenceRasters\sdn_px_area_100m.tif
set BUILDING_FOOTPRINT_SHAPEFILE_PATHS=D:\GRID\SDN\ECOPIA\AFRICA_SUDAN_building_32634.shp;D:\GRID\SDN\ECOPIA\AFRICA_SUDAN_building_32635.shp;D:\GRID\SDN\ECOPIA\AFRICA_SUDAN_building_32636.shp;D:\GRID\SDN\ECOPIA\AFRICA_SUDAN_building_32637.shp
set RELEASE_DATE=20200512
set CODE_VERSION=V02
set METADATA_DIR=D:\GRID\metadata

