set COUNTRY_CODE=SEN
set RASTER_GRID_PATH=D:\GRID\ReferenceRasters\sen_px_area_100m.tif
set BUILDING_FOOTPRINT_SHAPEFILE_PATHS=D:\GRID\SEN\ECOPIA\AFRICA_SENEGAL_building_32628.shp;D:\GRID\SEN\ECOPIA\AFRICA_SENEGAL_building_32629.shp
set RELEASE_DATE=20200625
set CODE_VERSION=V02
set METADATA_DIR=D:\GRID\metadata

