set COUNTRY_CODE=SLE
set RASTER_GRID_PATH=D:\GRID\ReferenceRasters\sle_px_area_100m.tif
set BUILDING_FOOTPRINT_SHAPEFILE_PATHS=D:\GRID\SLE\DIGITAL_GLOBE\AFRICA_SIERRA_LEONE_building_32628.shp;D:\GRID\SLE\DIGITAL_GLOBE\AFRICA_SIERRA_LEONE_building_32629.shp
set RELEASE_DATE=20200114
set CODE_VERSION=V02
set METADATA_DIR=D:\GRID\metadata

