set COUNTRY_CODE=SSD
set RASTER_GRID_PATH=D:\GRID\ReferenceRasters\ssd_px_area_100m.tif
set BUILDING_FOOTPRINT_SHAPEFILE_PATHS=D:\GRID\SSD\DIGITAL_GLOBE\South_Sudan_UTM35N.shp;D:\GRID\SSD\DIGITAL_GLOBE\South_Sudan_UTM36N.shp
set CODE_VERSION=V02
set RELEASE_DATE=20200114
set METADATA_DIR=D:\GRID\metadata

