set COUNTRY_CODE=STP
set RASTER_GRID_PATH=D:\GRID\ReferenceRasters\stp_px_area_100m.tif
set BUILDING_FOOTPRINT_SHAPEFILE_PATHS=D:\GRID\STP\ECOPIA\AFRICA_SAOTOMEANDPRINCIPE_building_32632.shp;D:\GRID\STP\ECOPIA\AFRICA_SAOTOMEANDPRINCIPE_building_32732.shp
set RELEASE_DATE=20200422
set CODE_VERSION=V02
set METADATA_DIR=D:\GRID\metadata

