set COUNTRY_CODE=TGO
set RASTER_GRID_PATH=D:\GRID\ReferenceRasters\tgo_px_area_100m.tif
set BUILDING_FOOTPRINT_SHAPEFILE_PATHS=D:\GRID\TGO\ECOPIA\AFRICA_TOGO_building_32630.shp;D:\GRID\TGO\ECOPIA\AFRICA_TOGO_building_32631.shp
set RELEASE_DATE=20200525
set CODE_VERSION=V02
set METADATA_DIR=D:\GRID\metadata

