set COUNTRY_CODE=TZA
set RASTER_GRID_PATH=D:\GRID\ReferenceRasters\tza_px_area_100m.tif
set BUILDING_FOOTPRINT_SHAPEFILE_PATHS=D:\GRID\TZA\DIGITAL_GLOBE\AFRICA_TANZANIA_building_32735.shp;D:\GRID\TZA\DIGITAL_GLOBE\AFRICA_TANZANIA_building_32736.shp;D:\GRID\TZA\DIGITAL_GLOBE\AFRICA_TANZANIA_building_32737.shp
set RELEASE_DATE=20200425
set CODE_VERSION=V02
set METADATA_DIR=D:\GRID\metadata

