set COUNTRY_CODE=ZMB
set RASTER_GRID_PATH=D:\GRID\ReferenceRasters\GRID3_ZMB_mastergrid.tif
set BUILDING_FOOTPRINT_SHAPEFILE_PATHS=D:\GRID\ZMB\DIGITAL_GLOBE\AFRICA_ZAMBIA_building_32734.shp;D:\GRID\ZMB\DIGITAL_GLOBE\AFRICA_ZAMBIA_building_32735.shp;D:\GRID\ZMB\DIGITAL_GLOBE\AFRICA_ZAMBIA_building_32736.shp
set RELEASE_DATE=20200114
set CODE_VERSION=V02
set METADATA_DIR=D:\GRID\metadata

