set COUNTRY_CODE=GHA
set RASTER_GRID_PATH=D:\GRID\ReferenceRasters\gha_px_area_100m.tif
set BUILDING_FOOTPRINT_SHAPEFILE_PATHS=D:\GRID\GHA\ECOPIA\AFRICA_GHANA_building_year2.gdb\AFRICA_GHANA_building_32630_year2;D:\GRID\GHA\ECOPIA\AFRICA_GHANA_building_year2.gdb\AFRICA_GHANA_building_32631_year2
set RELEASE_DATE=20201222
set CODE_VERSION=ALPHA
